### ISSUE TITLE
Incorrect import paths on python3

### ISSUE THREAD

**Issue by OzymandiasTheGreat** [Tungsteno74/pyWinhook#1]
I just installed pyWinhook on windows with python 3.6 and it threw an exception on import.
After looking into it, I changed `from HookManager import *` to `from .HookManager import *` and
`import cpyHook` to `from . import cpyHook` and it seems to work fine so far.

**Comment by Tungsteno74** [comment]
Hello, Have you checked if the changes also work on Python 2.x ? 
If yes add a pull request and i merge it in the master.
