### ISSUE TITLE
Unicode title error

### ISSUE THREAD

**Issue by arithxp** [Tungsteno74/pyWinhook#5]
if I switch widows than show this error message.

TypeError: KeyboardSwitch() missing 8 required positional arguments: 'msg', 'vk_code', 'scan_code', 'ascii', 'flags', 'time', 'hwnd', and 'win_name'

can you fix this error?
please help

**Comment by hoechenberger** [comment]
https://github.com/Answeror/pyhook_py3k seems to contain the required fixes. We should probably patch pyWinhook too.

**Comment by Tungsteno74** [comment]
@arithxp  I can't replicate the error, please can post the code that give you this error?

@hoechenberger   please can you point to the fixes to this error?

thanks

**Comment by hoechenberger** [comment]
> @arithxp I can't replicate the error, please can post the code that give you this error?

You need a window that has unicode characters in its name, like Skype, and then try to use `pyWinhook` with it. This is a known problem: https://stackoverflow.com/questions/26156633/pythoncom-crashes-on-keydown-when-used-hooked-to-certain-applications

> @hoechenberger please can you point to the fixes to this error?

Unfortunately they don't provide a clear patch set; we'd have to diff `pyHook_py3k`'s code base against `pyHook`'s. Or simply apply the fix that was mentioned on SO (see link above).

**Comment by hoechenberger** [comment]
@Tungsteno74 I believe that's the (most important?) commit:
https://github.com/Answeror/pyhook_py3k/commit/639ac766beed90f0a2dd7951a790314ff8c955ed

**Comment by Tungsteno74** [comment]
@hoechenberger well, it seems a minor fix.  
Are you working on it? If yes, you are free to send it to the master and update it on pypi with a minor version increase. (otherwise I will do it in the next few days)

**Comment by arithxp** [comment]
> 
> 
> https://github.com/Answeror/pyhook_py3k seems to contain the required fixes. We should probably patch pyWinhook too.

I also tried that. not fixed.
just closed program without error massages

and I found correct package
PyHook3 (https://github.com/gggfreak2003/PyHook3)

**Comment by hoechenberger** [comment]
<strike>@arithxp Have you tried applying this fix: 
https://github.com/Answeror/pyhook_py3k/pull/3 ?</strike> 

Never mind, didn’t see your reference to PyHook3 when I first wrote the comment.

I wonder if PyHook3 works with Python 2.7 too?

**Comment by arithxp** [comment]
> 
> 
> @arithxp Have you tried applying this fix:
> [Answeror/pyhook_py3k#3](https://github.com/Answeror/pyhook_py3k/pull/3) ?
> 
> Never mind, didn’t see your reference to PyHook3 when I first wrote the comment.
> 
> I wonder if PyHook3 works with Python 2.7 too?

I dont know.
but found this.
https://sourceforge.net/p/pyhook/bugs/1/

**Comment by Tungsteno74** [comment]
@hoechenberger 
> I wonder if PyHook3 works with Python 2.7 too?

It's avaiable on [PYPI](https://pypi.org/project/pyHook-3k-compiled/#files), but the only Wheel present is for Python 3.4, an old release (May 15, 2016).

[This other one](https://pypi.org/project/PyHook3/#files) is available for both versions, but equally old.

**Comment by Tungsteno74** [comment]
Well, now the error happened to me too. It also happens with Chrome window.

**Comment by hoechenberger** [comment]
@Tungsteno74 I'm still uncertain about which patch set to use. My gut feeling is that the patches from `pyWinhook_py3k` would be the way to go, but @arithxp pointed out that didn't work properly for them, only the (much smaller) patch set of `pyHook3` did, which doesn't do any of the unicode decoding stuff that `pyWinhook_py3k` does. So I'm wondering whether `pyHook3` actually works correctly (and reports the correct window names), or whether it simply works such that it doesn't throw an error ;) Currently don't have time to test anything though :\

**Comment by Tungsteno74** [comment]
@hoechenberger No problem :)
Currently, I'm still trying to understand better which problem cause this bug and how to fix it (`pyWinhook_py3k` also seems to me the right way).
In any case, I'm testing it with both Python latest versions (although I still use _version 2.7.x_) thus, in the next days when (and  if) I'll have fixed it, I hope someone else can test the improvements made in the `dev-1.6.1 branch`, with all others versions of _Python3_.

**Comment by Tungsteno74** [comment]
@arithxp @hoechenberger  hey guys, i fixed this bug on branch dev-1.6.1. 
If you have some time please test it with Python 3 versions that you use. I wait a few days before merging it in the main one.
Thanks

**Comment by arithxp** [comment]
> 
> 
> @arithxp @hoechenberger hey guys, i fixed this bug on branch dev-1.6.1.
> If you have some time please test it with Python 3 versions that you use. I wait a few days before merging it in the main one.
> Thanks

Thank you for updating.
It's works with Python 3.7 !!!!
👍

**Comment by hoechenberger** [comment]
Cool! Can test later tonight or tomorrow.

So you adopted some changes from PyHook3 and pyWinhook_3k? Maybe we should add an acknowledgement? :)
