### ISSUE TITLE
pyWinhook 1.6.1 release archive on GitHub contains pyWinhook 1.6.0

### ISSUE THREAD

**Issue by hoechenberger** [Tungsteno74/pyWinhook#9]
I'm not sure what went wrong there, maybe the release tag points to the wrong commit; in any case, when retrieving the source zip from https://github.com/Tungsteno74/pyWinhook/releases/tag/1.6.1, the archive contains `pyWinhook` 1.6.0, not 1.6.1. The sdist on PyPI is correct.

**Comment by Tungsteno74** [comment]
You have right, i think it is caused by a previous version created with a wrong commit. Github web interface do not permit to delete release tags. I'm checking if i can delete it locally by _Git Extensions_.

**Comment by hoechenberger** [comment]
Well tags can be removed via `git tag -d TAG`, but I believe the cleanest solution would be to do a new, correctly-tagged release.

**Comment by Tungsteno74** [comment]
> Well tags can be removed via `git tag -d TAG`, but I believe the cleanest solution would be to do a new, correctly-tagged release.

Yes i know, but i like to use _Git Extensions_ :)

Anyhow i fixed it!
Cheers

**Comment by hoechenberger** [comment]
Cool, thanks!
